// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: store_connection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreDriver int32

const (
	StoreDriver_SD_NONE StoreDriver = 0
	StoreDriver_SD_ORM  StoreDriver = 1
)

// Enum value maps for StoreDriver.
var (
	StoreDriver_name = map[int32]string{
		0: "SD_NONE",
		1: "SD_ORM",
	}
	StoreDriver_value = map[string]int32{
		"SD_NONE": 0,
		"SD_ORM":  1,
	}
)

func (x StoreDriver) Enum() *StoreDriver {
	p := new(StoreDriver)
	*p = x
	return p
}

func (x StoreDriver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreDriver) Descriptor() protoreflect.EnumDescriptor {
	return file_store_connection_proto_enumTypes[0].Descriptor()
}

func (StoreDriver) Type() protoreflect.EnumType {
	return &file_store_connection_proto_enumTypes[0]
}

func (x StoreDriver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreDriver.Descriptor instead.
func (StoreDriver) EnumDescriptor() ([]byte, []int) {
	return file_store_connection_proto_rawDescGZIP(), []int{0}
}

type StoreConnection struct {
	state         protoimpl.MessageState
	Password      string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Schema        string `protobuf:"bytes,6,opt,name=schema,proto3" json:"schema,omitempty"`
	SchemaGame    string `protobuf:"bytes,7,opt,name=schema_game,json=schemaGame,proto3" json:"schema_game,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	User          string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	Port          int64 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MaxConnection int64 `protobuf:"varint,8,opt,name=max_connection,json=maxConnection,proto3" json:"max_connection,omitempty"`
	sizeCache     protoimpl.SizeCache
	Driver        StoreDriver `protobuf:"varint,1,opt,name=driver,proto3,enum=pb.StoreDriver" json:"driver,omitempty"`
}

func (x *StoreConnection) Reset() {
	*x = StoreConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_connection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConnection) ProtoMessage() {}

func (x *StoreConnection) ProtoReflect() protoreflect.Message {
	mi := &file_store_connection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConnection.ProtoReflect.Descriptor instead.
func (*StoreConnection) Descriptor() ([]byte, []int) {
	return file_store_connection_proto_rawDescGZIP(), []int{0}
}

func (x *StoreConnection) GetDriver() StoreDriver {
	if x != nil {
		return x.Driver
	}
	return StoreDriver_SD_NONE
}

func (x *StoreConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StoreConnection) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StoreConnection) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StoreConnection) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *StoreConnection) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *StoreConnection) GetSchemaGame() string {
	if x != nil {
		return x.SchemaGame
	}
	return ""
}

func (x *StoreConnection) GetMaxConnection() int64 {
	if x != nil {
		return x.MaxConnection
	}
	return 0
}

var File_store_connection_proto protoreflect.FileDescriptor

var file_store_connection_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xf2, 0x01, 0x0a,
	0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x27, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61,
	0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2a, 0x26, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x44, 0x5f, 0x4f, 0x52, 0x4d, 0x10, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x6f, 0x68, 0x64,
	0x61, 0x64, 0x61, 0x2f, 0x67, 0x32, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_connection_proto_rawDescOnce sync.Once
	file_store_connection_proto_rawDescData = file_store_connection_proto_rawDesc
)

func file_store_connection_proto_rawDescGZIP() []byte {
	file_store_connection_proto_rawDescOnce.Do(func() {
		file_store_connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_connection_proto_rawDescData)
	})
	return file_store_connection_proto_rawDescData
}

var file_store_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_connection_proto_goTypes = []interface{}{
	(StoreDriver)(0),        // 0: pb.StoreDriver
	(*StoreConnection)(nil), // 1: pb.StoreConnection
}
var file_store_connection_proto_depIdxs = []int32{
	0, // 0: pb.StoreConnection.driver:type_name -> pb.StoreDriver
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_store_connection_proto_init() }
func file_store_connection_proto_init() {
	if File_store_connection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_connection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_connection_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_connection_proto_goTypes,
		DependencyIndexes: file_store_connection_proto_depIdxs,
		EnumInfos:         file_store_connection_proto_enumTypes,
		MessageInfos:      file_store_connection_proto_msgTypes,
	}.Build()
	File_store_connection_proto = out.File
	file_store_connection_proto_rawDesc = nil
	file_store_connection_proto_goTypes = nil
	file_store_connection_proto_depIdxs = nil
}
