// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: game/game_type.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameType int32

const (
	GameType_GT_NONE      GameType = 0
	GameType_GT_UNIVERSAL GameType = 1
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "GT_NONE",
		1: "GT_UNIVERSAL",
	}
	GameType_value = map[string]int32{
		"GT_NONE":      0,
		"GT_UNIVERSAL": 1,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_game_type_proto_enumTypes[0].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_game_game_type_proto_enumTypes[0]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_game_game_type_proto_rawDescGZIP(), []int{0}
}

type GameTypeForPayment int32

const (
	GameTypeForPayment_GTFP_NONE GameTypeForPayment = 0
)

// Enum value maps for GameTypeForPayment.
var (
	GameTypeForPayment_name = map[int32]string{
		0: "GTFP_NONE",
	}
	GameTypeForPayment_value = map[string]int32{
		"GTFP_NONE": 0,
	}
)

func (x GameTypeForPayment) Enum() *GameTypeForPayment {
	p := new(GameTypeForPayment)
	*p = x
	return p
}

func (x GameTypeForPayment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameTypeForPayment) Descriptor() protoreflect.EnumDescriptor {
	return file_game_game_type_proto_enumTypes[1].Descriptor()
}

func (GameTypeForPayment) Type() protoreflect.EnumType {
	return &file_game_game_type_proto_enumTypes[1]
}

func (x GameTypeForPayment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameTypeForPayment.Descriptor instead.
func (GameTypeForPayment) EnumDescriptor() ([]byte, []int) {
	return file_game_game_type_proto_rawDescGZIP(), []int{1}
}

var File_game_game_type_proto protoreflect.FileDescriptor

var file_game_game_type_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2a,
	0x29, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x47,
	0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x54, 0x5f, 0x55,
	0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x10, 0x01, 0x2a, 0x23, 0x0a, 0x12, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0d, 0x0a, 0x09, 0x47, 0x54, 0x46, 0x50, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x42,
	0x27, 0x5a, 0x25, 0x6f, 0x68, 0x64, 0x61, 0x64, 0x61, 0x2f, 0x67, 0x32, 0x67, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_game_type_proto_rawDescOnce sync.Once
	file_game_game_type_proto_rawDescData = file_game_game_type_proto_rawDesc
)

func file_game_game_type_proto_rawDescGZIP() []byte {
	file_game_game_type_proto_rawDescOnce.Do(func() {
		file_game_game_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_game_type_proto_rawDescData)
	})
	return file_game_game_type_proto_rawDescData
}

var file_game_game_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_game_type_proto_goTypes = []interface{}{
	(GameType)(0),           // 0: pb.game.GameType
	(GameTypeForPayment)(0), // 1: pb.game.GameTypeForPayment
}
var file_game_game_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_game_type_proto_init() }
func file_game_game_type_proto_init() {
	if File_game_game_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_game_type_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_game_type_proto_goTypes,
		DependencyIndexes: file_game_game_type_proto_depIdxs,
		EnumInfos:         file_game_game_type_proto_enumTypes,
	}.Build()
	File_game_game_type_proto = out.File
	file_game_game_type_proto_rawDesc = nil
	file_game_game_type_proto_goTypes = nil
	file_game_game_type_proto_depIdxs = nil
}
